export {
  EMAIL as EMAIL_PLACEHOLDER,
  PASSWORD as PASSWORD_PLACEHOLDER
} from './placeholders'

export {
  EMAIL as EMAIL_ERROR_MSG,
  REQUIRED as REQUIRED_ERROR_MSG,
  PASSWORD as PASSWORD_ERROR_MSG,
  INVALID_AUDIO_TYPE,
  INVALID_IMAGE_TYPE,
  INVALID_GAME_NAME,
  INVALID_GAME_NAME_HELP
} from './errorMessages'

export {
  EMAIL as EMAIL_VALIDATION,
  REQUIRED as REQUIRED_VALIDATION,
  PASSWORD as PASSWORD_VALIDATION,
  FIELD_GAME_NAME_VALIDATION,
  LOGIN_SYNC_VALIDATION
} from './validations'
